### ISSUE TITLE
Aqualink RS Pool Only

### ISSUE THREAD

**Issue by AUPoolUser** [sfeakes/AqualinkD#23]
### **Pool Only Aqualink RS 8 Revision MMM**

I have mapped most buttons to the one-touch buttons:
Button 01 	Filter Pump
Button 02	Not sure what this does on a Pool Only Aqualink RS – it usually controls a Spa in an Aqualink Pool and Spa Version. I see no need for it in the Pool Only Aqualink.
Button 03	Aux 1
Button 04	Aux 2
Button 05	Aux 3
Button 06	Aux 4
Button 07	Aux 5
Button 08	Aux 6
Button 09	Aux 7
Button 10	Temp 1
Button 11	Temp 2
Button 12	Solar Heater

**Issues Identified on Aqualink Pool Only**
The only issues so far identified relate to Temp1 and Temp2.

The Temp1 and Temp2 functions do not work properly in a Pool Only version of Aqualink. These would normally be the Pool Heater and Spa Heater temperature settings respectively in the Pool and Spa Aqualink.

**Temp1/Temp2 Issues Identified for F versus C**
Programing of the Temp1 and Temp2 buttons when pressed on the AqualinkD webpage appear to be for Farenheit only, even though my system is in Celcius. I would assume this is a problem also for Pool and Spa Users trying to program the Pool Heater and Spa Heater. 

Notwithstanding, setting Temp1 or Temp2 temperature even if I switch my system to Farenheit does not save the actual temperature programmed.

**If Filter Pump is OFF**
-	If I activate Temp2, it comes up with “communication error” after 2 seconds for about 5 seconds duration. It then illuminates and says “Heating to 0” - rather than the setpoint.
-	If I activate Temp1 while Temp2 is activated, Temp1 successfully illuminates but also states “Heating to 0” - rather than the setpoint. Also, when Temp1 is activated along with Temp2, Temp2 should show "enabled" rather than off while Temp1 is on.
-   Also while Temp1 is activated, if I try to enable Temp2 I get a “Connection Error” although this goes away after about 20-40 seconds

**If Filter Pump is ON:**
-	Temp2 occassionally flashes the Spa Water Temperature which appears to be derived from the Pool Water Temperature – otherwise it generally shows "--“
-	When Pressing Temp2, it briefly illuminates, activates the Aqualink Temp2 function but is not illuminated on the AqualinkD webpage, while being enabled on the OneTouch panel. This generally produces a communications error.
-	Temp2 is able to be turned off successfully.
-	Pressing Temp1 briefly illuminates the Button 10 and activates the Temp1 function, but does not remain illuminated.
-	Temp1 is able to be turned off successfully.

**If the Filter Pump is in DELAY mode (i.e. during coll down cycle):** it generally acts in the same way as if the pump is off.

Regards

Frank

**FYI ONLY ABOUT TEMP1 & TEMP2**
The OneTouch Panel allows a user to program Temp1 and Temp2 from 1 degrees celcius to 40 degrees celcius included so long as Temp2 must be lower than Temp1. Therefore, effectively in reality Temp1 can be 2 to 40, while Temp2 can be 1 to 39. In Farenheit its 34 to 104.

What is Temp1 and Temp2 supposed to do (from an old Aqualink owners manual):
“Temp1 is the priority (high) temperature. It must be set higher than Temp2, and it overrides Temp2 whenever it is enabled. Set temperature for Temp1 before setting temperature for Temp2.
Temp2 is the maintenance (low) temperature. It must be set lower than Temp1. If Temp2 is on and Temp1 is activated, Temp2 will turn off and its LED will flash when Temp1 is turned off again, Temp2 will re-activate.”

“On pool only and spa only units, you may set two separate temperatures for the pool or spa. Press the Temp1 button to heat to one temperature and the Temp2 button to heat to another.”

**Comment by sfeakes** [comment]
Thanks for all this information, I think I have an understanding of why.
I saw Temp1 and Temp2 for the first time a few weeks ago, the heater temp / setpoint messages are usually very different on all the other control panels I've seen previously.  When I saw the Temp1, Temp2 messages I put in a VERY quick fix to support the reading of these messages only, not the setting of the Temp1 and Temp2 messages. In that quick fix I forced units to F.  So that explains most of the issues you are seeing.

So now I need to understand why your panel are saying Temp1 and Temp2 vs the usual Pool temp setpoint and Spa temp setpoint, as the whole way to change these settings is different, and I haven't been able to get my panel into a config that replicates this. I'm wondering if it's simply a "pool only" config vs "pool & spa" config, or if it's more to do with the type / way the heater is attached and controlled by the control panel.
The only heaters I've come across so far have built in thermostats that are controlled via the RS458 buss, I *think* maybe your heater doesn't have a builtin thermostat and the aqualink control panel is acting as the thermostat for the heater and this is where the Temp1 and Temp2 come in, rather than just setting it as a setpoint. Do you know if your heater is controlled via the RS485 buss, or if the Control Panel is acting as the thermostat and turning simply turning it on and off?

I'll start digging through the documentation and see if I can find some information. Can you / have you used the Simulator yet?  If not, can you use the simulator and see if you can change the Temp1 and Temp2 settings through that.  If you can if would be really helpful if you put AqualinkD in debug mode, use the simulator to change Temp1 and send me the logs.

To close these issues out completely, will probably take a lot of back and forth between us, it may be best to use personal email and post in this thread once finished.  The "communication error" is a little concerning, I'd love to see the debug logs from that as well, as I think there may be more to that than simply trying to change the setpoint in the incorrect manor.

BTW. Sorry you have these issues, all this had to be reverse engineered as there is no documentation / information available, and your config is different to any I've seen before, so I couldn't account for it.

**Comment by sfeakes** [comment]
Fixed in latest updates.
