### ISSUE TITLE
Solar Heater is in the simulator and API but not the old or current web screen.

### ISSUE THREAD

**Issue by bigjsl** [sfeakes/AqualinkD#24]
Huge thanks for this project. I have had an RS485 adaptor in my draw for about three years waiting for time to reverse engineer the protocol and now this to come along!  

Plugged everything together today and got almost everything working pretty much immediately.

Brilliant!

I have a solar heater that can be turned on or off connected to the solar aux output.

It does not have a temperature set point, because it is plumbed separately, has its own sensors and does not require the main pump to be running.

aqualinkd knows it's there and I can turn the solar relay on and off via the API and the Simulator.

But I could not see it on the web interface or the old web interface.

I did some digging. 

I found issue 9 which reported a bug that caused Solar Heater to not appear unless dzidx was set for that button. Also noted that the bug was reported as fixed.

I did some more digging and found Solar_Heater commented out in /var/www/aqualinkd/config.js

Uncommenting and restarting and flushing some caches and it's all good. 

Is this just something that needs more elegant handling? 

Or am I subverting elegant handling that isn't working properly? 

jsl

**Comment by sfeakes** [comment]
Great, glad to know it’s all working.  I need to document the solar heater better. Since most don’t have one I use it as an example of how to remove devices from the UI.  I should state that better in the documentation.

Thanks very much for posting.   If you get chance can you click the Aqualinkd label in the web UI and the version of the control panel should be displayed.  Let me know what that is and I can add it to documentation as working version# if it’s a version I haven’t seen before.

**Comment by bigjsl** [comment]
B0029221 rev T
